# https://doc.rust-lang.org/cargo/reference/workspaces.html
[workspace]
resolver = "3"
members = ["lib", "cli"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/rvnkcode/dawn"

[workspace.dependencies]
anyhow = "1.0.102"
dawn = { path = "lib" }
mockall = "0.14.0"
thiserror = "2.0.18"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage)'] }
