# https://doc.rust-lang.org/cargo/reference/workspaces.html
[workspace]
resolver = "3"
members = ["lib", "cli", "gui/src-tauri"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/rvnkcode/dawn"

[workspace.dependencies]
anyhow = "1.0.104"
dawn = { path = "lib" }
regex = "1.13.1"
thiserror = "2.0.19"
uuid = { version = "1.24.0", features = ["v4"] }

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage)'] }
