[package]
name = "dawn-gui"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "dawn_gui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
dawn.workspace = true
tauri = { version = "2.11.5", features = [] }
