# https://github.com/rustsec/audit-check?tab=readme-ov-file#audit-changes
name: Cargo Audit

on:
  pull_request:
    branches: [main, stable]
    types: [opened, synchronize, reopened]
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - uses: actions/cache@v5
        with:
          path: ~/.cargo/advisory-db
          key: advisory-db-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: advisory-db-
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-audit
      - run: cargo audit
