# https://doc.rust-lang.org/cargo/guide/continuous-integration.html
name: CI

on:
  push:
    branches: [main, stable]
  pull_request:
    branches: [main, stable]
    types: [opened, synchronize, reopened]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      # https://github.com/Swatinem/rust-cache
      - uses: Swatinem/rust-cache@v2
      # https://github.com/rust-lang/rustfmt?tab=readme-ov-file#checking-style-on-a-ci-server
      - run: cargo fmt --all -- --check
      # Exclude GUI(Tauri) from core CI since it requires webkit system deps and built dist/,
      # and verify it with a full build in tauri.yml
      # https://github.com/rust-lang/rust-clippy?tab=readme-ov-file#travis-ci
      - run: cargo clippy --workspace --exclude dawn-gui --all-targets -- -D warnings
      - run: cargo test --workspace --exclude dawn-gui
