# https://doc.rust-lang.org/cargo/guide/continuous-integration.html
name: Rust

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths:
      - "**/*.rs"
      - "**/Cargo.toml"
      - "Cargo.lock"
      - "rustfmt.toml"
      - ".github/workflows/rust.yaml"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@d1031067263f94b142dd6c0ce24c5eb9d02d52a0 # master
        with:
          toolchain: stable
          components: rustfmt, clippy
      # https://github.com/Swatinem/rust-cache
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2
      # https://github.com/rust-lang/rustfmt?tab=readme-ov-file#checking-style-on-a-ci-server
      - run: cargo fmt --all -- --check
      # https://github.com/rust-lang/rust-clippy?tab=readme-ov-file#travis-ci
      - run: cargo clippy --workspace --all-targets -- -D warnings
      # TODO: Add tests when implemented
